sourcegraph/jsonrpc2

- jsonrpc2.go
- object_test.go
This makes the MarshalJSON/UnmarshalJSON methods centralize the logic, instead of requiring callers to occasionally munge responses to make them valid to later JSON-marshal.
> better null handling in (Request).params and (Response).result

- call_opt.go
- jsonrpc2.go
- jsonrpc2_test.go
SetID allows a caller to control the ID of the request. Previously it was
impossible to set the ID of a call.
> Add CallOpt SetID

- jsonrpc2.go
Also document that Meta is not part of the JSONRPC2 spec.
> Add Meta field to Response

- .travis.yml
It is failing the tests. This may actually be an underlying issue in the tests,
but not a big deal to fix now.
> ci: disable testing tip

- async.go
- jsonrpc2.go
- jsonrpc2_test.go
We have strict ordering requirements of how we handle FileSystem requests in
LSP. As such relying on the ordering the goroutine scheduler runs requests in
leads to potential out of order mutations to the FS. As such we update the
jsonrpc2 implementation to by default block until Handle returns (note it can
still respond to the request at a later stage). For more simple use cases we
provide the AsyncHandler which will work like the previous implementation.
> Handle is blocking

- jsonrpc2.go
The 'result' key MUST be unset according when the error key is set.
This is not what is happening right now. When the error is set,
"result":null is returned in the response payload. This patch is fixing
the issue by adding omitempty for the result field.
Fixes #13
> Response: Add omitempty tag for Result

- handler_with_error.go
See the description of `SuppressErrClosed` for details.
Helps https://github.com/sourcegraph/sourcegraph/issues/9595
>  add support for suppressing ErrClosed in HandlerWithError logs

- stream.go
It is optional, and we are sending the default value. https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#header-part
Notably the rust language server doesn't support receiving it.
> remove content type from vscode object codec

- conn_opt.go
This is necessary for using other loggers. But we can still use the logger from stdlib.
> Replaced log.Logger parameter by interface

- go.mod
@sqs recent go.mod addition will break compatibility for go 1.12 (currently supported) version
> support for go 1.12+

- codec_test.go
- stream.go
The library currently contains the following codecs:
* `VSCodeObjectCodec`
* `VarintObjectCodec`
The commit in this MR adds a third codec called PlainObjectCodec that does not have a header in the message. It only uses Go's `json.Encoder`/`json.Decoder` to encode/decode messages.
> Add PlainObjectCodec

- stream.go
fix typo in jsonrpc2/stream.go comment
s/encoed/encode
> fix typo in jsonrpc2/stream.go

- jsonrpc2.go
This change makes the treatment of params and meta the same, by
assigning a well-known pointer at first to detect if the unmarshaling
process overwrites it with an explicit nil, or it stays the same in
which it means that it was unset from the beginning.
> Homogenize treatment of params and meta in UnmarshalJSON

- conn_opt.go
- conn_opt_test.go
Before this commit, a custom logger could be set with the LogMessages function. However, by using LogMessages not only is a custom logger set but also all received and sent messages are logged. Use cases exist where a custom logger is desired to log errors but not all messages.
> Add ability to set custom logger

- jsonrpc2_test.go
- stream.go
This change fixes a bug that causes PlainObjectCodec to
lose additional messages from stream. json.Decoder has
an internal buffer that reads more than one message, but
is discarded after every use. Now PlainObjectCodec reuses
encoder and decoder within a buffered stream, however
using it directly in your code retains the old, incorrect
behaviour.
A user should now use plainObjectStream if he needs
plain JSON-RPC 2.0 stream without headers.
`NewPlainObjectStream` method has been added for this reason.
fixes #57
> [#57] Fix and deprecate PlainObjectCodec

- .github/workflows/ci.yml
Update to actions/checkout@v3 to avoid deprecation warning
Created as part of batch change: [_Created by Sourcegraph batch change `sourcegraph-operator-dax/Upgrade_actions_checkout_v2-v3`._](https://sourcegraph.sourcegraph.com/users/sourcegraph-operator-dax/batch-changes/Upgrade_actions_checkout_v2-v3)
> ci: update to actions/checkout@v3

- call_opt.go
- call_opt_test.go
- jsonrpc2.go
The JSON-RPC 2.0 specification allows the params member of a request to be omitted [1]. Before this commit, this library did not allow the params member to be omitted when sending a request. When the params argument of the Conn.Call/Conn.DispatchCall or Conn.Notify method was set to nil, then Request.Params was set to the JSON encoding of nil which is null.
This commit adds a CallOption named OmitNilParams. If OmitNilParams is used when sending a request with params set to nil, then the params member in the JSON encoding of Request is omitted. If the OmitNilParams option is not used then the previous behavior is maintained. In other words, the changes in this commit are backwards compatible.
References
[1]: https://www.jsonrpc.org/specification#request_object
> Add ability to omit params member from request

- .github/workflows/ci.yml
The CI pipeline has been broken in this project for some time because the latest version of staticcheck is not compatible with every version of Go. Through trial and error, it was discovered that staticcheck v0.2.2 is the latest version that is compatible with Go 1.16.
The authors of staticcheck also recommend pinning the version in CI pipelines to prevent unintentional breakage of the build [1].
References
[1]: https://staticcheck.io/docs/running-staticcheck/ci/github-actions/#version
> Pin staticcheck version to v0.2.2

- jsonrpc2.go
- jsonrpc2_test.go
Please expand the commit messages for details.
> Fix underlying connection not being closed on protocol error

- jsonrpc2.go
- jsonrpc2_test.go
The JSON-RPC 2.0 specification allows the data member of an error object to be omitted. Before this commit, if Error.Data was nil then the JSON encoding was "null". That means that the data member was included in every JSON-RPC error object, even when the data member was not explicitly set.
This commit adds the omitempty struct tag to the Error.Data field, meaning that the data member is omitted from the JSON encoding unless explicitly set with the Error.SetError() method. Beware that this is a breaking change for clients that may have strict null checks on the data member.
> Omit data field from error when empty

- call_opt.go
- call_opt_test.go
- conn.go
- conn_test.go
- example_test.go
- jsonrpc2.go
- jsonrpc2_test.go
- request.go
- request_test.go
- response_test.go
With this commit, the JSON encoding of `Request` always omits the params member when calling `Conn.Call`, `Conn.DispatchCall`, or `Conn.Notify` with the `params` argument set to `nil`. This change also removes the `OmitNilParams` call option that was added in commit 8012d496 (#62).
As of this commit, if users desire to send a JSON-RPC request with a `params` value of `null`, then they may do so by explicitly setting the `params` argument of `Conn.Call`/`Conn.DispatchCall`/`Conn.Notify` to `json.RawMessage("null")`.
> Always omit params member from request when empty

- conn_opt.go
- conn_opt_test.go
As documented: OnRecv causes all requests received on conn to invoke f(req, nil) and all responses to invoke f(req, resp).
Since OnRecv is called with both *Request and *Response being non-nil when we're handling a response, we need to check that *Response is non-nil before we check *Request is non-nil. This change just swaps the two cases in the switch statement to fix the issue. For consistency, I've swapped the cases for OnSend also, even when it's not needed.
> Fix logging of received response messages

- .github/workflows/ci.yml
- .github/workflows/lsif.yml
Closes #72
On the [lsif.yml](https://github.com/sourcegraph/jsonrpc2/blob/master/.github/workflows/lsif.yml) file I couldn't be 100% sure on the permissions required on the lsif-go job, so I let only with `contents: read` for now -- let me know if this should be changed.
Note that the permissions defined on the [line 5](https://github.com/sourcegraph/jsonrpc2/compare/master...diogoteles08:jsonrpc2:master?expand=1#diff-ec41b80d233edd86dd5759adb6cb14e5a0a9d5d7eb6e849000b398c4dd143310R5) will be the same permissions granted on the [line 17](https://github.com/sourcegraph/jsonrpc2/compare/master...diogoteles08:jsonrpc2:master?expand=1#diff-ec41b80d233edd86dd5759adb6cb14e5a0a9d5d7eb6e849000b398c4dd143310R17), as the `secrets.GITHUB_TOKEN` passed as parameter is the same token that will be used …
> ci: set minimal permissions to GitHub workflows

- SECURITY.md
Closes #74
I've created the SECURITY.md file following a GitHub's template and considering that you'd request that users report vulnerabilities through the [security advisory](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability), which is a handy new GitHub feature, but it's still in beta and **has to be manually enabled by a maintainer**.
If you're interested in this feature, you can activate it following this steps:
1. Click on this [link](https://github.com/sourcegraph/jsonrpc2/settings/security_analysis) to go to Code security & analysis section on your repo's settings
2. Click "Enable" for "Private vulnerability reporting (Beta)"
However, if you'd rather not use this feature, you can also request …
> Docs: Create Security Policy

- .github/dependabot.yml
Closes #77 
Reminder: as mentioned on the issue, I also strongly recommend that you enable the **_Dependabot security updates_** option on [Code security and analysis](https://github.com/sourcegraph/jsonrpc2/settings/security_analysis) to receive out of schedule upgrades in case of a new security patch is released (avoiding being exposed for much time).
Thanks!
> CI: Enable dependabot to keep CI up to date

- conn.go
- conn_opt.go
- handler_with_error.go
- request.go
This is behaviorally transparent: existing tests pass.
This will be easier to review in [hide-whitespace](https://github.com/sourcegraph/jsonrpc2/pull/83/files?w=1) mode.
> transparently simplify control flow

- conn.go
- conn_test.go
- jsonrpc2.go
The changes in this pull request cancel the context that is given to the [Handler](https://pkg.go.dev/github.com/sourcegraph/jsonrpc2#Handler) when the connection is closed.
Before this change, the user of this library had to do something like this:
```go
ctx, cancel := context.WithCancel(context.Background())
conn := jsonrpc2.NewConn(ctx, myStream, myHandler)
// Cancel context when the connection is disconnected.
go func() {
<-conn.DisconnectNotify()
cancel()
}()
```
Having to manually cancel the context when the connection is disconnected is unexpected. For comparison, the following is what the documentation states for the request context in the [net/http](https://pkg.go.dev/net/http#Request.Context) package:
> For incoming server requests, the context is canceled when the client's …
> Cancel Handler context when connection closes
